language: node_js

node_js:
  - "7.8.0"

install:
  - npm config set spin=false
  - npm install -g coveralls
  - npm install

script:
  - npm test
  - npm run coverage
  - coveralls < ./coverage/lcov.info || true 

sudo: false
